### ISSUE TITLE
Prettier shouldn't be a dependency

### ISSUE THREAD

**Issue by KaySackey** [iamolegga/prettier-loader#3]
Prettier shouldn't be both a dependency and a peerDependency.

It'll force an install of prettier even if you have a higher versioned but still compatible package.

**Comment by iamolegga** [comment]
Hello, @KaySackey , thanks for issue!

Yes, you are right about `dependency`, I think, I should move it from `dependency` to `devDependency`.

But I'm not sure about `peerDependency`, because I think, it must log warnings if developer use prettier < 1.6, where it started to use `cosmiconfig`, which `prettier-loader` use too to load user's config.

What do you think?

**Comment by iamolegga** [comment]
Solved in 2.0.0
